/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otp.generator;

import java.sql.Timestamp;;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;

/**
 *
 * @author pushp
 */
public class HOME extends javax.swing.JFrame {
    public String publicOTP ="";
    /**
     * Creates new form HOME
     */
    public HOME() {
        initComponents();
        OTPVerify.hide();
        resend.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        OTPVerify = new javax.swing.JPanel();
        otp = new javax.swing.JTextField();
        resend = new javax.swing.JLabel();
        btnOTP = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnVerify = new javax.swing.JButton();
        email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OTPVerify.setBackground(new java.awt.Color(0, 51, 102));
        OTPVerify.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        otp.setBackground(new java.awt.Color(0, 51, 102));
        otp.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        otp.setForeground(new java.awt.Color(255, 255, 255));
        OTPVerify.add(otp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 220, 30));

        resend.setBackground(new java.awt.Color(255, 0, 0));
        resend.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        resend.setForeground(new java.awt.Color(255, 0, 0));
        resend.setText("Resend OTP");
        resend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resendMouseClicked(evt);
            }
        });
        OTPVerify.add(resend, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 100, 30));

        btnOTP.setBackground(new java.awt.Color(0, 51, 102));
        btnOTP.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnOTP.setForeground(new java.awt.Color(255, 255, 255));
        btnOTP.setText("Verify OTP");
        btnOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOTPActionPerformed(evt);
            }
        });
        OTPVerify.add(btnOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 180, -1));

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("OTP");
        OTPVerify.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 220, 30));

        jPanel1.add(OTPVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 560, 140));

        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email Address");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 220, 30));

        btnVerify.setBackground(new java.awt.Color(0, 51, 102));
        btnVerify.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnVerify.setForeground(new java.awt.Color(255, 255, 255));
        btnVerify.setText("Verify Email");
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 180, -1));

        email.setBackground(new java.awt.Color(0, 51, 102));
        email.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        // TODO add your handling code here:
        
        Timestamp time1 =Time.getTimestemp();
        
        if(email.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Enter Email Address");
        }
        else{
                OTPVerify.show();
        String OTP=OTPGenerator.generateOTP(6);
        publicOTP=OTP;
        try {
            OTPGenerator.sendEmail(OTP,email.getText());
        } catch (MessagingException ex) {
            Logger.getLogger(HOME.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void btnOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOTPActionPerformed
        // TODO add your handling code here:
        if(OTPGenerator.verifyOTP(otp, publicOTP)){
        JOptionPane.showMessageDialog(null, "Email Verified");
        this.dispose();
        publicOTP="";
        }
        else{
        JOptionPane.showMessageDialog(null, "OTP do not match!!");  
        resend.show();
        }
    }//GEN-LAST:event_btnOTPActionPerformed

    private void resendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resendMouseClicked
        // TODO add your handling code here:
        String OTP=OTPGenerator.generateOTP(6);
        publicOTP=OTP;
        try {
            OTPGenerator.sendEmail(OTP,email.getText());
        } catch (MessagingException ex) {
            Logger.getLogger(HOME.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "OTP SEND");
        resend.hide();
        
    }//GEN-LAST:event_resendMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OTPVerify;
    private javax.swing.JButton btnOTP;
    private javax.swing.JButton btnVerify;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField otp;
    private javax.swing.JLabel resend;
    // End of variables declaration//GEN-END:variables
}
